[package]
name        = "rustsec"
description = "Client library for the RustSec security advisory database"
version     = "0.23.3" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <bascule@gmail.com>"]
license     = "Apache-2.0 OR MIT"
homepage    = "https://rustsec.org"
repository  = "https://github.com/rustsec/rustsec-crate/"
readme      = "README.md"
categories  = ["api-bindings", "development-tools"]
keywords    = ["audit", "rustsec", "security", "advisory", "vulnerability"]
edition     = "2018"

[dependencies]
cargo-lock = { version = "6", default-features = false }
crates-index = { version = "0.16", optional = true }
cvss = { version = "1", features = ["serde"] }
fs-err = "2.5"
git2 = { version = "0.13", optional = true }
home = { version = "0.5", optional = true }
humantime = { version = "2", optional = true }
humantime-serde = { version = "1", optional = true }
platforms = { version = "1", features = ["serde"] }
semver = { version = "0.11", features = ["serde"] }
semver-parser = { version = "0.10", optional = true }
serde = { version = "1", features = ["serde_derive"] }
smol_str = "=0.1.17" # Pinned to avoid MSRV breakages
thiserror = "1"
toml = "0.5"
url = { version = "2", features = ["serde"] }

[dependencies.cargo-edit]
version = "0.7"
optional = true
default-features = false
features = ["upgrade"]

[dev-dependencies]
tempfile = "3"
once_cell = "1"

[features]
default = ["git"]
fix = ["cargo-edit", "semver-parser"]
git = ["crates-index", "git2", "home", "humantime", "humantime-serde"]
dependency-tree = ["cargo-lock/dependency-tree"]
vendored-openssl = ["git2/vendored-openssl"]

[package.metadata.docs.rs]
all-features = true

[patch.crates-io]
semver = { git = 'https://github.com/Shnatsel/semver.git' }
